apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: password-frontend
  template:
    metadata:
      labels:
        app: password-frontend
    spec:
      containers:
      - name: frontend
        image: tunesky34/password-manager-frontend:v3
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VITE_API_URL